version: '3.9'

services:
      
  postgres-book:
    image: postgres
    container_name: postgres-book
    ports:
      - '${DATABASE_PORT}:5432'
    restart: always
    env_file:
      - .env
    volumes:
      - ../../data/:/var/lib/postgresql/data

  backend-book:
    container_name: backend-book
    image: backend/book:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres-book
    restart: always
    ports:
      - 9060:9060
