version: '3.9'

services:
  postgres-book:
    image: postgres
    container_name: postgres
    ports:
      - '${DATABASE_PORT}:5432'
    restart: always
    env_file:
      - ../../.env
    volumes:
      - ../../data/:/var/lib/postgresql/data
